version: "3.2"

services:
  postgres:
    image: postgres:9-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: janobono/zookeeper:3
    networks:
      - backend
    volumes:
      - zookeeper-log:/zookeeper/log
      - zookeeper-data:/zookeeper/data

  kafka:
    image: janobono/kafka:2
    depends_on:
      - zookeeper
    networks:
      - backend
    volumes:
      - kafka-log:/kafka/log
      - kafka-data:/kafka/data

  spring-boot-nut:
    image: janobono/spring-boot-nut-chocolate:latest
    environment:
      - NUT_DB_URL=jdbc:postgresql://postgres:5432/test
      - NUT_DB_USER=test
      - NUT_DB_PASSWORD=test
      - NUT_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - 8082:8080
    networks:
      - backend
    depends_on:
      - postgres
      - kafka

networks:
  backend:

volumes:
  postgres-data:
  zookeeper-log:
  zookeeper-data:
  kafka-log:
  kafka-data:
