# ===============================
# = LOGGING
# ===============================
logging:
  level:
    sk.janobono: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# ===============================
# = JPA / HIBERNATE
# ===============================
spring:
  datasource:
    url: ${NUT_DB_URL}
    username: ${NUT_DB_USER}
    password: ${NUT_DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  flyway:
    check-location: true

  # ===============================
  # = KAFKA
  # ===============================
  kafka:
    consumer:
      bootstrap-servers: ${NUT_KAFKA_BOOTSTRAP_SERVERS}
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${NUT_KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
