quarkus:
  datasource:
    url: ${NUT_DB_URL}
    driver: ${NUT_DB_DRIVER:org.postgresql.Driver}
    username: ${NUT_DB_USER}
    password: ${NUT_DB_PASSWORD}
  flyway:
    migrate-at-start: true

bootstrap-servers: ${NUT_KAFKA_BOOTSTRAP_SERVERS}
